# Generated by Django 4.1.1 on 2022-10-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_location_lat_alter_location_lng_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "Пользователь"),
                    ("ADMIN", "Админ"),
                    ("MODERATOR", "Модератор"),
                ],
                default="member",
                max_length=12,
            ),
        ),
    ]
